export const data = [
  {
    job_id: "r_hLq-Jfp9WUgYXsAAAAAA==",
    employer_name: "Virtual Labs Inc.",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA9OH5DuWLqRSUSnT-gKp71L9DkYvLDhd-XkVX&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_employment_type: "CONTRACTOR",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-at-virtual-labs-inc-3844363651",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6911,
    job_description:
      "Job Title: Python Developer with TypeScript\n\nLocation: Sunnyvale, CA or Dallas, TX or Seattle, WA\n\nJob Description:\n\nWe are seeking a skilled Python Developer with proficiency in TypeScript to join our dynamic team. As a Python Developer, you will be responsible for designing, developing, and maintaining high-quality software solutions. Your expertise in Python combined with TypeScript will be crucial in building robust and scalable applications that meet our clients' needs. You will collaborate closely with cross-functional teams to deliver innovative solutions while adhering to best practices and coding standards.\n\nResponsibilities:\n\nDesign, develop, and maintain efficient Python applications.\n\nWrite clean, scalable, and maintainable code using TypeScript for frontend development.\n\nCollaborate with other team members to define, design, and ship new features.\n\nTroubleshoot and debug issues to ensure optimal performance and reliability.\n\nImplement security and data protection measures.\n\nParticipate in code reviews and provide constructive feedback to peers.\n\nStay updated with emerging technologies and incorporate them into the development process.\n\nWork closely with stakeholders to understand requirements and translate them into technical solutions.\n\nDocument code and technical designs for future reference.\n\nRequirements:\n\nBachelor's degree in Computer Science, Engineering, or related field.\n\nProven experience as a Python Developer with a strong understanding of Python frameworks such as Django or Flask.\n\nProficiency in TypeScript and experience with frontend frameworks such as Angular or React.\n\nSolid understanding of object-oriented programming principles.\n\nFamiliarity with RESTful APIs and web services.\n\nExperience with relational databases such as PostgreSQL or MySQL.\n\nStrong problem-solving skills and attention to detail.\n\nExcellent communication and collaboration abilities.\n\nAbility to work effectively in a fast-paced environment and meet deadlines.\n\nExperience with version control systems such as Git is a plus.\n\nKnowledge of Docker and containerization technologies is desirable.\n\nPrior experience in Agile development methodologies is advantageous.",
    job_is_remote: false,
    job_posted_at_timestamp: 1709820974,
    job_posted_at_datetime_utc: "2024-03-07T14:16:14.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&q=r_hLq-Jfp9WUgYXsAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=r_hLq-Jfp9WUgYXsAAAAAA%3D%3D&htidocid=r_hLq-Jfp9WUgYXsAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-06T14:16:14.000Z",
    job_offer_expiration_timestamp: 1712412974,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science, Engineering, or related field",
        "Proven experience as a Python Developer with a strong understanding of Python frameworks such as Django or Flask",
        "Proficiency in TypeScript and experience with frontend frameworks such as Angular or React",
        "Solid understanding of object-oriented programming principles",
        "Familiarity with RESTful APIs and web services",
        "Experience with relational databases such as PostgreSQL or MySQL",
        "Strong problem-solving skills and attention to detail",
        "Excellent communication and collaboration abilities",
        "Ability to work effectively in a fast-paced environment and meet deadlines",
        "Prior experience in Agile development methodologies is advantageous",
      ],
      Responsibilities: [
        "As a Python Developer, you will be responsible for designing, developing, and maintaining high-quality software solutions",
        "Your expertise in Python combined with TypeScript will be crucial in building robust and scalable applications that meet our clients' needs",
        "You will collaborate closely with cross-functional teams to deliver innovative solutions while adhering to best practices and coding standards",
        "Design, develop, and maintain efficient Python applications",
        "Write clean, scalable, and maintainable code using TypeScript for frontend development",
        "Collaborate with other team members to define, design, and ship new features",
        "Troubleshoot and debug issues to ensure optimal performance and reliability",
        "Implement security and data protection measures",
        "Participate in code reviews and provide constructive feedback to peers",
        "Stay updated with emerging technologies and incorporate them into the development process",
        "Work closely with stakeholders to understand requirements and translate them into technical solutions",
        "Document code and technical designs for future reference",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    estimated_salaries: [
      {
        location: "Dallas, TX",
        job_title: "Python Developer",
        publisher_name: "Indeed",
        publisher_link:
          "https://www.indeed.com/career/python-developer/salaries/Dallas--TX",
        min_salary: 94453.87077096451,
        max_salary: 155230.49120410252,
        median_salary: 121087.24439854166,
        salary_period: "YEAR",
        salary_currency: "USD",
      },
      {
        location: "Dallas, TX",
        job_title: "Python Developer",
        publisher_name: "ZipRecruiter",
        publisher_link:
          "https://www.ziprecruiter.com/Salaries/Python-Developer-Salary-in-Dallas,TX",
        min_salary: 39.71154,
        max_salary: 76.09471,
        median_salary: 53.075645,
        salary_period: "HOUR",
        salary_currency: "USD",
      },
      {
        location: "Dallas, TX",
        job_title: "Python Developer",
        publisher_name: "Monster",
        publisher_link:
          "https://www.monster.com/salary/q-python-developer-l-dallas-tx",
        min_salary: 107694,
        max_salary: 138306,
        median_salary: 120293,
        salary_period: "YEAR",
        salary_currency: "USD",
      },
    ],
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-at-virtual-labs-inc-3844363651",
        is_direct: false,
      },
    ],
    employer_reviews: [],
  },
]
