export const data = [
  {
    job_id: "r_hLq-Jfp9WUgYXsAAAAAA==",
    employer_name: "Virtual Labs Inc.",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA9OH5DuWLqRSUSnT-gKp71L9DkYvLDhd-XkVX&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_employment_type: "CONTRACTOR",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-at-virtual-labs-inc-3844363651",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6911,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-at-virtual-labs-inc-3844363651",
        is_direct: false,
      },
    ],
    job_description:
      "Job Title: Python Developer with TypeScript\n\nLocation: Sunnyvale, CA or Dallas, TX or Seattle, WA\n\nJob Description:\n\nWe are seeking a skilled Python Developer with proficiency in TypeScript to join our dynamic team. As a Python Developer, you will be responsible for designing, developing, and maintaining high-quality software solutions. Your expertise in Python combined with TypeScript will be crucial in building robust and scalable applications that meet our clients' needs. You will collaborate closely with cross-functional teams to deliver innovative solutions while adhering to best practices and coding standards.\n\nResponsibilities:\n\nDesign, develop, and maintain efficient Python applications.\n\nWrite clean, scalable, and maintainable code using TypeScript for frontend development.\n\nCollaborate with other team members to define, design, and ship new features.\n\nTroubleshoot and debug issues to ensure optimal performance and reliability.\n\nImplement security and data protection measures.\n\nParticipate in code reviews and provide constructive feedback to peers.\n\nStay updated with emerging technologies and incorporate them into the development process.\n\nWork closely with stakeholders to understand requirements and translate them into technical solutions.\n\nDocument code and technical designs for future reference.\n\nRequirements:\n\nBachelor's degree in Computer Science, Engineering, or related field.\n\nProven experience as a Python Developer with a strong understanding of Python frameworks such as Django or Flask.\n\nProficiency in TypeScript and experience with frontend frameworks such as Angular or React.\n\nSolid understanding of object-oriented programming principles.\n\nFamiliarity with RESTful APIs and web services.\n\nExperience with relational databases such as PostgreSQL or MySQL.\n\nStrong problem-solving skills and attention to detail.\n\nExcellent communication and collaboration abilities.\n\nAbility to work effectively in a fast-paced environment and meet deadlines.\n\nExperience with version control systems such as Git is a plus.\n\nKnowledge of Docker and containerization technologies is desirable.\n\nPrior experience in Agile development methodologies is advantageous.",
    job_is_remote: false,
    job_posted_at_timestamp: 1709820974,
    job_posted_at_datetime_utc: "2024-03-07T14:16:14.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=r_hLq-Jfp9WUgYXsAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-06T14:16:14.000Z",
    job_offer_expiration_timestamp: 1712412974,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science, Engineering, or related field",
        "Proven experience as a Python Developer with a strong understanding of Python frameworks such as Django or Flask",
        "Proficiency in TypeScript and experience with frontend frameworks such as Angular or React",
        "Solid understanding of object-oriented programming principles",
        "Familiarity with RESTful APIs and web services",
        "Experience with relational databases such as PostgreSQL or MySQL",
        "Strong problem-solving skills and attention to detail",
        "Excellent communication and collaboration abilities",
        "Ability to work effectively in a fast-paced environment and meet deadlines",
        "Prior experience in Agile development methodologies is advantageous",
      ],
      Responsibilities: [
        "As a Python Developer, you will be responsible for designing, developing, and maintaining high-quality software solutions",
        "Your expertise in Python combined with TypeScript will be crucial in building robust and scalable applications that meet our clients' needs",
        "You will collaborate closely with cross-functional teams to deliver innovative solutions while adhering to best practices and coding standards",
        "Design, develop, and maintain efficient Python applications",
        "Write clean, scalable, and maintainable code using TypeScript for frontend development",
        "Collaborate with other team members to define, design, and ship new features",
        "Troubleshoot and debug issues to ensure optimal performance and reliability",
        "Implement security and data protection measures",
        "Participate in code reviews and provide constructive feedback to peers",
        "Stay updated with emerging technologies and incorporate them into the development process",
        "Work closely with stakeholders to understand requirements and translate them into technical solutions",
        "Document code and technical designs for future reference",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "hjzhdjz6Idl6rz-nAAAAAA==",
    employer_name: "Diverse Lynx",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1VeJ-13QmOtMzKA9tD3EqAjYEEE_de6dl51G3&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-at-diverse-lynx-3844892603",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6879,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-at-diverse-lynx-3844892603",
        is_direct: false,
      },
      {
        publisher: "Monster",
        apply_link:
          "https://www.monster.com/job-openings/python-developer-austin-tx--cd45216b-0e17-4fbf-9560-17cc86c456f0",
        is_direct: false,
      },
      {
        publisher: "Talentify",
        apply_link:
          "https://www.talentify.io/job/python-developer-austin-texas-diverse-lynx-23-69826",
        is_direct: false,
      },
    ],
    job_description:
      "Hi,\n\nWelcome to Diverse Lynx! We combine industry leading expertise and our personal dedication to help you find your next career opportunity. We are a Minority and Women Owned Business Enterprise (MWBE) certified by the State of New Jersey and Minority Business Enterprise (MBE) certified from National Minority Supplier Development Council.\n\nEstablished in 2002, we have helped thousands of candidates find their next role. Diverse Lynx is headquartered in Princeton, NJ and have exclusive job opportunities with Fortune companies in USA, Canada, United Kingdom, and India. We would love to speak with you and help get connected with the hiring team for this role.\n\nBenefits/Perks\n• Competitive Compensation\n• Flexible work models (Remote, Hybrid, Onsite)\n• Career Growth Opportunities\n• Exclusivity on all roles meaning your resume will be personally reviewed by hiring managers\n• Long Term Contracts\n• Medical Benefits\n\nPlease go through below opening we have with one of our leading global professional services firm delivering outcomes that transform business and shape the future. Kindly review the details and let me know if you would like to apply and further discuss.\n\nRole: Python Developer\n\nType: FTE\n\nLocation: Austin TX (5 days onsite)\n\nMust have skills: Python, Python frameworks like Django, Flask, Pandas, Restful APIs\n\nThe ideal candidate will have experience working with Snowflake, Oracle, Autosys, and Niagara platforms and exposure to AWS. As a Python Developer, you will be responsible for developing and maintaining data-driven applications, implementing machine learning algorithms and optimizing data workflows. Good to have some knowledge on finance.\n\nResponsibilities\n• Writing efficient, reusable, testable, and scalable code\n• Understanding, analyzing, and implementing Business needs, feature modification requests, conversion into software components\n• Integration of user-oriented elements into different applications, data storage solutions\n• Developing Backend components to enhance performance and receptiveness, server-side logic, and platform, statistical learning models, highly responsive web applications\n• Designing and implementing High availability and low latency applications, data protection and security features\n• Performance tuning and automation of application\n• Testing and debugging software applications with Python test framework tools like Behave, Pytest, PyUnit, etc.\n• Enhancing the functionalities of current software systems\n• Coming up with digital tools for online traffic monitoring\n• Working with Python libraries like Pandas, NumPy, etc.\n• Creating predictive models for AI and Client-based features\n• Keeping abreast with the latest technology and trends\n• Fine-tune and develop AI/Client-based algorithms based on results\n\nTechnical Skills\n\nGood proficiency in,\n• Python frameworks like Django, Flask, etc.\n• Web frameworks and RESTful APIs\n• Core Python fundamentals and programming\n• Code packaging, release, and deployment\n• Database knowledge\n• Circles, conditional and control statements\n• Object-relational mapping\n• Server-side languages like Mako etc.\n• Code versioning tools like Git, SVN, etc.",
    job_is_remote: false,
    job_posted_at_timestamp: 1709849047,
    job_posted_at_datetime_utc: "2024-03-07T22:04:07.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: ["health_insurance"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=hjzhdjz6Idl6rz-nAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-03T04:09:02.000Z",
    job_offer_expiration_timestamp: 1712117342,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Must have skills: Python, Python frameworks like Django, Flask, Pandas, Restful APIs",
        "The ideal candidate will have experience working with Snowflake, Oracle, Autosys, and Niagara platforms and exposure to AWS",
        "Good to have some knowledge on finance",
        "Good proficiency in,",
        "Web frameworks and RESTful APIs",
        "Core Python fundamentals and programming",
        "Code packaging, release, and deployment",
        "Database knowledge",
        "Circles, conditional and control statements",
        "Object-relational mapping",
        "Server-side languages like Mako etc",
        "Code versioning tools like Git, SVN, etc",
      ],
      Responsibilities: [
        "As a Python Developer, you will be responsible for developing and maintaining data-driven applications, implementing machine learning algorithms and optimizing data workflows",
        "Writing efficient, reusable, testable, and scalable code",
        "Understanding, analyzing, and implementing Business needs, feature modification requests, conversion into software components",
        "Integration of user-oriented elements into different applications, data storage solutions",
        "Developing Backend components to enhance performance and receptiveness, server-side logic, and platform, statistical learning models, highly responsive web applications",
        "Designing and implementing High availability and low latency applications, data protection and security features",
        "Performance tuning and automation of application",
        "Testing and debugging software applications with Python test framework tools like Behave, Pytest, PyUnit, etc",
        "Enhancing the functionalities of current software systems",
        "Coming up with digital tools for online traffic monitoring",
        "Working with Python libraries like Pandas, NumPy, etc",
        "Creating predictive models for AI and Client-based features",
        "Keeping abreast with the latest technology and trends",
        "Fine-tune and develop AI/Client-based algorithms based on results",
      ],
      Benefits: [
        "Competitive Compensation",
        "Flexible work models (Remote, Hybrid, Onsite)",
        "Career Growth Opportunities",
        "Exclusivity on all roles meaning your resume will be personally reviewed by hiring managers",
        "Long Term Contracts",
        "Medical Benefits",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "bbbV1xTh-aO2pBV-AAAAAA==",
    employer_name: "Mitchell Martin Inc.",
    employer_logo:
      "https://thebestandbrightest.com/wp-content/uploads/2020/12/MMI-logo.png",
    employer_website: "http://www.mitchellmartin.com",
    employer_company_type: null,
    job_publisher: "Recruit.net",
    job_employment_type: "CONTRACTOR",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.recruit.net/job/python-developer-jobs/34EEB9DA95283483",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4361,
    apply_options: [
      {
        publisher: "Recruit.net",
        apply_link:
          "https://www.recruit.net/job/python-developer-jobs/34EEB9DA95283483",
        is_direct: false,
      },
      {
        publisher: "Jobilize",
        apply_link:
          "https://www.jobilize.com/job/us-tx-python-developer-mitchell-martin-hiring-now-job-immediately",
        is_direct: false,
      },
    ],
    job_description:
      "• W2 ONLY, NO C2C *\n\nBE PART OF OUR GROWING TEAM!\n\nJob Title: Python Developer\n\nClient Location:Jersey City, NJ/Charlotte, NC/Plano, TX/Chicago, IL\n\nType: Contract\n\nCompetitive Salary awaits!\n\nOur client is a leading Investment bank in the US.\n\nThis position requires close collaboration with technical leads and product owners to provide data, analytics, and reporting functionalities on the GWD platform. The ideal candidate will have hands-on experience in building, testing, and deploying standard web and integration capabilities, including restAPI and data transformation...\n\nRequired Skills:\n• 8 to 10 years of experience with Python.\n• Experience with application development in an enterprise environment.\n• Experience with SQL databases, Angular, and Java.\n• Must have active hands-on development experience and be able to start coding from day one.\n• Experience with core libraries in Python and Angular.\n• Experience with implementing web applications that include Python.\n• Recent experience with Angular applications.\n• Experience with end-to-end implementation of web applications using Angular with a concentration on Python.\n• Must have prior experience with large-scale and full-scale end-to-end projects.\n• The product is already developed, so the main role would be to support and make small changes as needed - not new development, but enhancements and support.",
    job_is_remote: false,
    job_posted_at_timestamp: 1709856000,
    job_posted_at_datetime_utc: "2024-03-08T00:00:00.000Z",
    job_city: null,
    job_state: "TX",
    job_country: "US",
    job_latitude: 31.9686,
    job_longitude: -99.90181,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=bbbV1xTh-aO2pBV-AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-07T00:00:00.000Z",
    job_offer_expiration_timestamp: 1712448000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 96,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "The ideal candidate will have hands-on experience in building, testing, and deploying standard web and integration capabilities, including restAPI and data transformation..",
        "8 to 10 years of experience with Python",
        "Experience with application development in an enterprise environment",
        "Experience with SQL databases, Angular, and Java",
        "Must have active hands-on development experience and be able to start coding from day one",
        "Experience with core libraries in Python and Angular",
        "Recent experience with Angular applications",
        "Experience with end-to-end implementation of web applications using Angular with a concentration on Python",
        "Must have prior experience with large-scale and full-scale end-to-end projects",
        "The product is already developed, so the main role would be to support and make small changes as needed - not new development, but enhancements and support",
      ],
      Benefits: ["Competitive Salary awaits!"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "ZLHPTnm0vUZhlFhdAAAAAA==",
    employer_name: "Company Name",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRozpyZ2-Blq6K0b_7uk1IBsPMU6UbpYVLrjwqL&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Radley James",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer – Houston, TX (Hybrid)",
    job_apply_link:
      "https://www.radleyjames.com/job/python-developer-houston-tx-hybrid/",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7154,
    apply_options: [
      {
        publisher: "Radley James",
        apply_link:
          "https://www.radleyjames.com/job/python-developer-houston-tx-hybrid/",
        is_direct: false,
      },
      {
        publisher: "Learn4Good",
        apply_link:
          "https://www.learn4good.com/jobs/houston/texas/info_technology/2724195958/e/",
        is_direct: false,
      },
    ],
    job_description:
      "Python Developer\n\nHouston, Texas, United States (Hybrid)\n\nA leading hedge fund with a global reputation for being one of the best in the industry is looking to add a mid to senior developer to its Houston office.\n\nThis individual will be working on expanding their global analytics and trading-related tools and APIs, liaising between external and internal sources and tools of data and databases to create new pipelines as well as helping create analytics apps to be used by the traders, data scientists and quants.\n\nQualifications:\n• Computer science or related degree from a top university\n• 3+ years experience in Python, Beautiful Soup, Selenium, etc.\n• Experience with AWS, docker, Kubernetes are all a plus\n\nIndustry-leading compensation on offer with exceptional bonuses\n\nIf interested please get in touch by applying or at Volkan.ozbicer@radleyjames.com with your resume if you have further questions.",
    job_is_remote: false,
    job_posted_at_timestamp: 1694595106,
    job_posted_at_datetime_utc: "2023-09-13T08:51:46.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=ZLHPTnm0vUZhlFhdAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Computer science or related degree from a top university",
        "3+ years experience in Python, Beautiful Soup, Selenium, etc",
      ],
      Responsibilities: [
        "This individual will be working on expanding their global analytics and trading-related tools and APIs, liaising between external and internal sources and tools of data and databases to create new pipelines as well as helping create analytics apps to be used by the traders, data scientists and quants",
      ],
      Benefits: [
        "Industry-leading compensation on offer with exceptional bonuses",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "70TAzH8W_MHzd5k5AAAAAA==",
    employer_name: "Magnus Technology Solutions",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6jDxj9ijK5FI1q7aYX2LJr7YxTpzqyPhX_-tp&s=0",
    employer_website: "http://www.magnustechnol.com",
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer (Entry Level)",
    job_apply_link:
      "https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-(Entry-Level)/-in-Frisco,TX?jid=8078428a471c9c19",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.7249,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-(Entry-Level)/-in-Frisco,TX?jid=8078428a471c9c19",
        is_direct: true,
      },
    ],
    job_description:
      "We are seeking a Python Developer (Entry Level) to become an integral part of our team! You will be responsible for creating and modifying computer application software or specialized utility programs.\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n\nQualifications:\n• Previous experience in software development, computer engineering, or other related fields\n• Knowledge of Java, Python, or other programming languages\n• Familiarity with relational databases such as MySQL, Oracle, and SQL Server\n• Deadline and detail-oriented\n• Strong analytical and critical thinking skills\n\nCompany DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA. We work on #Selenium, #QA_Testing, #QA_Automation, #Manual_Testing #Dotnet, #java, #j2ee, #java_UI, #Angular, #React, #Python, #DevOps, #Salesforce, #Hadoop, #IOS, #Android, #RPA, #Mulesoft and any #Developer related #Technologies.",
    job_is_remote: true,
    job_posted_at_timestamp: 1709312545,
    job_posted_at_datetime_utc: "2024-03-01T17:02:25.000Z",
    job_city: "Frisco",
    job_state: "TX",
    job_country: "US",
    job_latitude: 33.150673,
    job_longitude: -96.82361,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=70TAzH8W_MHzd5k5AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-07T00:00:00.000Z",
    job_offer_expiration_timestamp: 1712448000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 80000,
    job_max_salary: 100000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "Previous experience in software development, computer engineering, or other related fields",
        "Knowledge of Java, Python, or other programming languages",
        "Familiarity with relational databases such as MySQL, Oracle, and SQL Server",
        "Deadline and detail-oriented",
        "Strong analytical and critical thinking skills",
        "Company DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA",
      ],
      Responsibilities: [
        "You will be responsible for creating and modifying computer application software or specialized utility programs",
        "Analyze user needs and develop software solutions",
        "Work with project manager or product owner to meet specification needs",
        "Recommend software upgrades to optimize operational efficiency",
        "Collaborate with other developers to design and optimize code",
        "Create flowcharts and user guides for new and existing programs",
        "Document all programming tasks and procedures",
        "Perform routine software maintenance",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_occupational_categories: [
      "15-1132.00: Software Developers, Applications",
    ],
  },
  {
    job_id: "N1Vou7tWxKoI8e1_AAAAAA==",
    employer_name: "Diverse Lynx",
    employer_logo:
      "https://c.smartrecruiters.com/sr-company-logo-prod-aws-dc5/57112fb7e4b08b394157ff4a/huge?r=s3-eu-central-1&_1460772472631",
    employer_website: "http://www.diverselynx.com",
    employer_company_type: null,
    job_publisher: "Adzuna",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer",
    job_apply_link: "https://www.adzuna.com/details/4598932261",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4787,
    apply_options: [
      {
        publisher: "Adzuna",
        apply_link: "https://www.adzuna.com/details/4598932261",
        is_direct: false,
      },
    ],
    job_description:
      "Python Developer\n\nSan Antonio, TX\n\nContract\n\nJD:\n\nPython Developer\n\nDiverse Lynx LLC is an Equal Employment Opportunity employer. All qualified applicants will receive due consideration for employment without any discrimination. All applicants will be evaluated solely on the basis of their ability, competence and their proven capability to perform the functions outlined in the corresponding role. We promote and support a diverse workforce across all levels in the company.",
    job_is_remote: false,
    job_posted_at_timestamp: 1709856000,
    job_posted_at_datetime_utc: "2024-03-08T00:00:00.000Z",
    job_city: null,
    job_state: "TX",
    job_country: "US",
    job_latitude: 31.9686,
    job_longitude: -99.90181,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=N1Vou7tWxKoI8e1_AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-03-22T14:28:15.000Z",
    job_offer_expiration_timestamp: 1711117695,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "59ZS7KlQNNgIZfFKAAAAAA==",
    employer_name: "Westinghouse Electric Company",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/WestinghouseLogo.svg/1200px-WestinghouseLogo.svg.png",
    employer_website: "http://www.westinghousenuclear.com",
    employer_company_type: "Construction",
    job_publisher: "Recruit.net",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.recruit.net/job/python-developer-jobs/11D13A1BAEC7A03C",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4304,
    apply_options: [
      {
        publisher: "Recruit.net",
        apply_link:
          "https://www.recruit.net/job/python-developer-jobs/11D13A1BAEC7A03C",
        is_direct: false,
      },
      {
        publisher: "Jobilize",
        apply_link:
          "https://www.jobilize.com/job/us-tx-python-developer-westinghouse-electric-company-hiring-now-job",
        is_direct: false,
      },
    ],
    job_description:
      "Position Description\n• Provides application software development services or technical support in more complex situations.\n• May also be responsible for requirements gathering and BRD/SRD preparation. Has thorough knowledge of the Software Development Life Cycle.\n• Conducts reviews of the test Plan and test Data. May allocate/ coordinate work within a team/project.\n• The job holder leads the technical design, development and documentation of cross-functional, multi-platform application systems.\n• S/he also ensures that expected application performance levels are achieved by coordinating, coding, testing, implementation and documentation.\n• Must have thorough and demonstrative knowledge on or both the user-side frontend of a website, as well as the backend, server-side that powers the user-side.\n• Additional requirements include intermediate understanding of security principles, relational databases and architecture design principles.\n• Programming well-designed, testable, efficient code.\n• Analyze, design and develop tests and test-automation suites. Develop flowcharts, layouts and documentation to satisfy requirements and solutions.\n\nEducation/Experience:\n• Bachelor's degree in computer science engineering or a related discipline, or equivalent work experience required.\n• Prior experience with using a specific application development toolkit and knowledge of front end and backend development coding languages such as C#, Java, HTML, NodeJS, CSS, JSON, Angular, JavaScript.\n• MANDATORY: experience/exposure in API development using Python",
    job_is_remote: false,
    job_posted_at_timestamp: 1709510400,
    job_posted_at_datetime_utc: "2024-03-04T00:00:00.000Z",
    job_city: null,
    job_state: "TX",
    job_country: "US",
    job_latitude: 31.9686,
    job_longitude: -99.90181,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=59ZS7KlQNNgIZfFKAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-03T00:00:00.000Z",
    job_offer_expiration_timestamp: 1712102400,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Must have thorough and demonstrative knowledge on or both the user-side frontend of a website, as well as the backend, server-side that powers the user-side",
        "Additional requirements include intermediate understanding of security principles, relational databases and architecture design principles",
        "Programming well-designed, testable, efficient code",
        "Bachelor's degree in computer science engineering or a related discipline, or equivalent work experience required",
        "Prior experience with using a specific application development toolkit and knowledge of front end and backend development coding languages such as C#, Java, HTML, NodeJS, CSS, JSON, Angular, JavaScript",
        "MANDATORY: experience/exposure in API development using Python",
      ],
      Responsibilities: [
        "Provides application software development services or technical support in more complex situations",
        "May also be responsible for requirements gathering and BRD/SRD preparation",
        "Has thorough knowledge of the Software Development Life Cycle",
        "Conducts reviews of the test Plan and test Data",
        "May allocate/ coordinate work within a team/project",
        "The job holder leads the technical design, development and documentation of cross-functional, multi-platform application systems",
        "S/he also ensures that expected application performance levels are achieved by coordinating, coding, testing, implementation and documentation",
        "Analyze, design and develop tests and test-automation suites",
        "Develop flowcharts, layouts and documentation to satisfy requirements and solutions",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_naics_code: "237",
    job_naics_name: "Heavy and Civil Engineering Construction",
  },
  {
    job_id: "Se73RDMZ0mXU9x1jAAAAAA==",
    employer_name: "Reece USA",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk3AoGfUp8KCgyugkW89_iK-oXwaCuTX5bH2Kd&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-at-reece-usa-3842330537",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6879,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-at-reece-usa-3842330537",
        is_direct: false,
      },
      {
        publisher: "Jobright AI",
        apply_link: "https://jobright.ai/jobs/info/65e04a99575dfd5a802a4bd0",
        is_direct: false,
      },
    ],
    job_description:
      'PLEASE NOTE THIS IS A PERMANENT POSITION. THE SUCCESSFUL APPLICANT MUST BE A US CITIZEN OR GREEN CARD HOLDER AS WE CANNOT PROVIDE ANY VISA SUPPORT. NO C2C or C2H OFFERED\n\nAbout the Role:\n\nWe are currently seeking a Python Developer It is 100% onsite at an office in Addison TX.\n\nOverview\n\nThe Reece Innovation team is growing! We’re looking for a Python Developer with an enthusiastic drive for Innovation and Artificial Intelligence. In this role, you\'ll become an integral part of a team thriving in a dynamic environment, crafting tools for the next generation of Reece employees and customers. Candidates successfully passing the initial two interview rounds will be required to complete a brief online coding test; please refrain from applying if you are unwilling to undertake the test.\n\nKey Responsibilities\n• Play an active role in solutions and developing new digital prototypes.\n• Collaborate within a team environment to transform approved prototypes into production-ready tools.\n• Embrace a "student of the business" mindset, understanding the "why" behind all prototypes and productionized tools.\n• Think creatively and contribute innovative ideas for digital tools, enhancing both customer and team member experiences.\n• Explore the application of different technologies, such as wearable computing, big data, IoT, and AI/machine learning, to solve real business problems.\n• Write clean, modular, high-quality, high-performance, and maintainable code.\n\nTech Stack\n• Python\n• Typescript\n• React\n• Docker\n• Lambda\n• AWS\n• EC2\n• Elasticsearch\n• Redis\n\nQualifications\n• 3-7 years in professional software engineering or data science, specifically leveraging Python for the development of AI-driven/related tools.\n• Bachelor\'s degree in computer science, engineering, mathematics, physics, or similar technical disciplines.\n• Strong knowledge of data structures, algorithms, and architectural patterns.\n• Experience in developing practical applications rather than solely focusing on research and development.\n• Experience with cloud platforms.\n• Strong English communication skills.\n\nNice-to-haves\n• M.S. degree in Computer Science, MBA, or related advanced degree preferred.\n• Previous startup experience.\n• Examples of projects led from start to finish as the lead Python developer.\n• Experience as a lead data scientist working on AI initiatives.\n• Understanding of automation and its optimization for business needs.\n• Exposure to big data and analytics would be advantageous.\n• Experience working in globally disbursed teams.\n• Bonus points for showing examples of projects you led that solved real-world problems (big or small!).\n\nIf you are interested please kindly apply with your up-to-date resume with contact details.\n\nBR\n\nPhil Cox',
    job_is_remote: false,
    job_posted_at_timestamp: 1709148662,
    job_posted_at_datetime_utc: "2024-02-28T19:31:02.000Z",
    job_city: "Addison",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.96179,
    job_longitude: -96.82917,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Se73RDMZ0mXU9x1jAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-03-29T19:31:02.000Z",
    job_offer_expiration_timestamp: 1711740662,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 115000,
    job_max_salary: 130000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "THE SUCCESSFUL APPLICANT MUST BE A US CITIZEN OR GREEN CARD HOLDER AS WE CANNOT PROVIDE ANY VISA SUPPORT",
        "3-7 years in professional software engineering or data science, specifically leveraging Python for the development of AI-driven/related tools",
        "Bachelor's degree in computer science, engineering, mathematics, physics, or similar technical disciplines",
        "Strong knowledge of data structures, algorithms, and architectural patterns",
        "Experience in developing practical applications rather than solely focusing on research and development",
        "Experience with cloud platforms",
        "Strong English communication skills",
        "Previous startup experience",
        "Examples of projects led from start to finish as the lead Python developer",
        "Experience as a lead data scientist working on AI initiatives",
        "Understanding of automation and its optimization for business needs",
        "Exposure to big data and analytics would be advantageous",
        "Experience working in globally disbursed teams",
        "Bonus points for showing examples of projects you led that solved real-world problems (big or small!)",
      ],
      Responsibilities: [
        "In this role, you'll become an integral part of a team thriving in a dynamic environment, crafting tools for the next generation of Reece employees and customers",
        "Play an active role in solutions and developing new digital prototypes",
        "Collaborate within a team environment to transform approved prototypes into production-ready tools",
        'Embrace a "student of the business" mindset, understanding the "why" behind all prototypes and productionized tools',
        "Think creatively and contribute innovative ideas for digital tools, enhancing both customer and team member experiences",
        "Explore the application of different technologies, such as wearable computing, big data, IoT, and AI/machine learning, to solve real business problems",
        "Write clean, modular, high-quality, high-performance, and maintainable code",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "K6ggc7eeCbBENoVFAAAAAA==",
    employer_name: "SimplyApply",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2NDVt7Y3gh59KrxKHVLtZTUF6t3NwgBi7NNJE&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_employment_type: "FULLTIME",
    job_title: "Senior Machine Learning Engineer (Python)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/senior-machine-learning-engineer-python-at-simplyapply-3850319469",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6842,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/senior-machine-learning-engineer-python-at-simplyapply-3850319469",
        is_direct: false,
      },
    ],
    job_description:
      "77 West Wacker Dr (35012), United States of America, Chicago, Illinois\n\nSenior Machine Learning Engineer (Python)\n\nAs a Capital One Machine Learning Engineer (MLE), you'll be part of an Agile team dedicated to productionizing machine learning applications and systems at scale. You'll participate in the detailed technical design, development, and implementation of machine learning applications using existing and emerging technology platforms. You'll focus on machine learning architectural design, develop and review model and application code, and ensure high availability and performance of our machine learning applications. You'll have the opportunity to continuously learn and apply the latest innovations and best practices in machine learning engineering.\n\nWhat You'll Do In The Role:\n• The MLE role overlaps with many disciplines, such as Ops, Modeling, and Data Engineering. In this role, you'll be expected to perform many ML engineering activities, including one or more of the following:\n• Design, build, and/or deliver ML models and components that solve real-world business problems, while working in collaboration with the Product and Data Science teams.\n• Inform your ML infrastructure decisions using your understanding of ML modeling techniques and issues, including choice of model, data, and feature selection, model training, hyperparameter tuning, dimensionality, bias/variance, and validation).\n• Solve complex problems by writing and testing application code, developing and validating ML models, and automating tests and deployment.\n• Collaborate as part of a cross-functional Agile team to create and enhance software that enables state-of-the-art big data and ML applications.\n• Retrain, maintain, and monitor models in production.\n• Leverage or build cloud-based architectures, technologies, and/or platforms to deliver optimized ML models at scale.\n• Construct optimized data pipelines to feed ML models.\n• Leverage continuous integration and continuous deployment best practices, including test automation and monitoring, to ensure successful deployment of ML models and application code.\n• Ensure all code is well-managed to reduce vulnerabilities, models are well-governed from a risk perspective, and the ML follows best practices in Responsible and Explainable AI.\n• Use programming languages like Python, Scala, or Java.\n\nBasic Qualifications:\n• Bachelor's degree\n• At least 4 years of experience programming with Python, Scala, or Java (Internship experience does not apply)\n• At least 3 years of experience designing and building data-intensive solutions using distributed computing\n• At least 2 years of on-the-job experience with an industry recognized ML frameworks (scikit-learn, PyTorch, Dask, Spark, or TensorFlow)\n• At least 1 year of experience productionizing, monitoring, and maintaining models\n\nPreferred Qualifications:\n• 1+ years of experience building, scaling, and optimizing ML systems\n• 1+ years of experience with data gathering and preparation for ML models\n• 2+ years of experience developing performant, resilient, and maintainable code\n• Experience developing and deploying ML solutions in a public cloud such as AWS, Azure, or Google Cloud Platform\n• Master's or doctoral degree in computer science, electrical engineering, mathematics, or a similar field\n• 3+ years of experience with distributed file systems or multi-node database paradigms\n• Contributed to open source ML software\n• Authored/co-authored a paper on a ML technique, model, or proof of concept\n• 3+ years of experience building production-ready data pipelines that feed ML models\n• Experience designing, implementing, and scaling complex data pipelines for ML models and evaluating their performance\n\nAt this time, Capital One will not Job Level: Hourly\n\nJob Type: Hourly Full Time\n\nWant to build a stronger, more sustainable future and cultivate your career? Join Cargill's global team of 155,000 employees who are committed to safe, responsible and sustainable ways to nourish the world. This position is in Cargill's protein and salt business, where we provide wholesome, high-quality food products to a wide range of customers, from foodservice operators and grocery stores to manufacturers and exporters.\n\nJob Location: Friona, TX\n\nJob Type: Full Time\n\nShift(s) Available: Rotating\n\nCompensation: $23.50 - $32.00/hr\n\nBenefits Information\n• Medical, Dental, Vision, and Prescription Drug Insurance\n• Health and Wellness Incentives\n• Paid Vacation and Holidays\n• 401(k) with Cargill matching contributions\n• Flexible Spending Accounts (FSAs)\n• Short-Term Disability and Life Insurance\n• Employee Assistance Program (EAP)\n• Tuition Reimbursement\n• Employee Discounts\n\nPrincipal Accountabilities\n• May operate heavy machinery (including forklift) or computer programs\n• Use a variety of tools and retrieve parts\n• Conduct daily set-up of area\n• Troubleshooting\n• Working around or with machinery and power sources such as electricity\n• Ensuring safety, food safety and quality\n• Cleanliness and housekeeping\n• Maintaining a safe working environment\n\nRequired Qualifications\n• Must be eligible to work in the United States without visa sponsorship\n• Must be 18 years or older\n• Ability to read, write, and speak English\n• Ability to perform basic math such as addition, subtraction, multiplication, and division\n• Knowledge of basic tools and maintenance related subjects\n• Willingness to participate on various teams such as HAZMAT\n\nPreferred Qualifications\n• Basic computer skills\n• Previous experience in maintenance\n• Previous Cargill experience\n• Work history in the past 12 months\n\nConsidered candidates will receive a phone call from a (952) area code. Please note that this position does not include relocation reimbursement.\n\nEqual Opportunity Employer, including Disability/Vet\n\nSimplyApply",
    job_is_remote: false,
    job_posted_at_timestamp: 1709900135,
    job_posted_at_datetime_utc: "2024-03-08T12:15:35.000Z",
    job_city: "Friona",
    job_state: "TX",
    job_country: "US",
    job_latitude: 34.641735,
    job_longitude: -102.724106,
    job_benefits: [
      "health_insurance",
      "paid_time_off",
      "retirement_savings",
      "dental_coverage",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=K6ggc7eeCbBENoVFAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-07T12:15:10.000Z",
    job_offer_expiration_timestamp: 1712492110,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 48,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree",
        "At least 4 years of experience programming with Python, Scala, or Java (Internship experience does not apply)",
        "At least 3 years of experience designing and building data-intensive solutions using distributed computing",
        "At least 2 years of on-the-job experience with an industry recognized ML frameworks (scikit-learn, PyTorch, Dask, Spark, or TensorFlow)",
        "At least 1 year of experience productionizing, monitoring, and maintaining models",
        "Must be eligible to work in the United States without visa sponsorship",
        "Must be 18 years or older",
        "Ability to read, write, and speak English",
        "Ability to perform basic math such as addition, subtraction, multiplication, and division",
        "Knowledge of basic tools and maintenance related subjects",
        "Willingness to participate on various teams such as HAZMAT",
      ],
      Responsibilities: [
        "As a Capital One Machine Learning Engineer (MLE), you'll be part of an Agile team dedicated to productionizing machine learning applications and systems at scale",
        "You'll participate in the detailed technical design, development, and implementation of machine learning applications using existing and emerging technology platforms",
        "You'll focus on machine learning architectural design, develop and review model and application code, and ensure high availability and performance of our machine learning applications",
        "You'll have the opportunity to continuously learn and apply the latest innovations and best practices in machine learning engineering",
        "The MLE role overlaps with many disciplines, such as Ops, Modeling, and Data Engineering",
        "In this role, you'll be expected to perform many ML engineering activities, including one or more of the following:",
        "Design, build, and/or deliver ML models and components that solve real-world business problems, while working in collaboration with the Product and Data Science teams",
        "Inform your ML infrastructure decisions using your understanding of ML modeling techniques and issues, including choice of model, data, and feature selection, model training, hyperparameter tuning, dimensionality, bias/variance, and validation)",
        "Solve complex problems by writing and testing application code, developing and validating ML models, and automating tests and deployment",
        "Collaborate as part of a cross-functional Agile team to create and enhance software that enables state-of-the-art big data and ML applications",
        "Retrain, maintain, and monitor models in production",
        "Leverage or build cloud-based architectures, technologies, and/or platforms to deliver optimized ML models at scale",
        "Construct optimized data pipelines to feed ML models",
        "Leverage continuous integration and continuous deployment best practices, including test automation and monitoring, to ensure successful deployment of ML models and application code",
        "Ensure all code is well-managed to reduce vulnerabilities, models are well-governed from a risk perspective, and the ML follows best practices in Responsible and Explainable AI",
        "Use programming languages like Python, Scala, or Java",
        "May operate heavy machinery (including forklift) or computer programs",
        "Use a variety of tools and retrieve parts",
        "Conduct daily set-up of area",
        "Troubleshooting",
        "Working around or with machinery and power sources such as electricity",
        "Ensuring safety, food safety and quality",
        "Cleanliness and housekeeping",
        "Maintaining a safe working environment",
      ],
      Benefits: [
        "Shift(s) Available: Rotating",
        "Compensation: $23.50 - $32.00/hr",
        "Medical, Dental, Vision, and Prescription Drug Insurance",
        "Health and Wellness Incentives",
        "Paid Vacation and Holidays",
        "401(k) with Cargill matching contributions",
        "Flexible Spending Accounts (FSAs)",
        "Short-Term Disability and Life Insurance",
        "Employee Assistance Program (EAP)",
        "Tuition Reimbursement",
        "Employee Discounts",
      ],
    },
    job_job_title: "Learning engineer",
    job_posting_language: "en",
    job_onet_soc: "15111100",
    job_onet_job_zone: "5",
  },
  {
    job_id: "QREkfaUXIQT_mPQqAAAAAA==",
    employer_name: "Rapid Technologies LLC",
    employer_logo: null,
    employer_website: "http://www.raptek.com",
    employer_company_type: null,
    job_publisher: "Adzuna",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer",
    job_apply_link: "https://www.adzuna.com/details/4595720267",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4913,
    apply_options: [
      {
        publisher: "Adzuna",
        apply_link: "https://www.adzuna.com/details/4595720267",
        is_direct: false,
      },
    ],
    job_description:
      "Title: Python Developer\n\nLocation: TX, NH, RI, NC, MA\n\nDuration: Long Term Contract\n\nRequirement:\n\nPython REST API Development core python skills needed Python Object oriented Details\n\nExperience with Database technology Cloud Native Databases like AWS RDS AWS Dynamodb Oracle etc\n\nAWS Services experience Development Serverless Queues Notification etc Kubernetes knowledge\n\nCKAD certification preferable\n\nCI CD knowledge using Jenkins is a must\n\nPlatforming Engineering",
    job_is_remote: false,
    job_posted_at_timestamp: 1709683200,
    job_posted_at_datetime_utc: "2024-03-06T00:00:00.000Z",
    job_city: "Bee Cave",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.306099,
    job_longitude: -97.95238,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=QREkfaUXIQT_mPQqAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-03-20T14:35:43.000Z",
    job_offer_expiration_timestamp: 1710945343,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Python REST API Development core python skills needed Python Object oriented Details",
        "Experience with Database technology Cloud Native Databases like AWS RDS AWS Dynamodb Oracle etc",
        "AWS Services experience Development Serverless Queues Notification etc Kubernetes knowledge",
        "CKAD certification preferable",
        "CI CD knowledge using Jenkins is a must",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
]
